import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./siteComponents/Header";
import Footer from "./siteComponents/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MoonMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="px-14">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
